config/routes.rb
Mywines::Application.routes.draw do
  get "charts/index"
  get "charts/timelines"
  get "charts/traits"
  get "charts/counts"

  get 'tastings/duplicate' => 'tastings#duplicate'
  resources :tastings

  post 'wines/guesser' => 'wines#guesser'
  resources :wines
  
  resources :users
  
  match 'classification/index' => 'classification#index'
  match 'classification/add_classification' => 'classification#add_classification'
  match 'classification/add_classification_bulk' => 'classification#add_classification_bulk'
  match 'classification/show' => 'classification#show'

  root :to => 'wines#index'

end

app/models/wine.rb
class Wine < ActiveRecord::Base
  attr_accessible :name, :photo, :price, :vineyard_id, :vintage, :varietal, :purchased
  attr_accessor :photo_file_name
  attr_accessor :photo_content_type
  attr_accessor :photo_file_size
  attr_accessor :photo_updated_at
  
  validates :name, :presence => true

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "20x20>" }, :default_url => "/images/default_wine.png"
  
  has_many :tastings, :dependent => :destroy
  has_many :users, :through => :tastings
  
  belongs_to :vineyard

  def get_heritage
    v = self.vineyard
    s = v.subregion
    r = s.region
    c = r.country
    return {:vineyard => v.name, :subregion => s.name, :region => r.name, :country => c.name}
  end
  
  def pretty_name
    "#{self.name} (#{self.varietal} - #{self.vineyard.subregion.region.name}, #{self.vineyard.subregion.region.country.name})"
  end
  
  def avg_rating
    tastings = self.tastings
    if tastings.length == 0
      return false
    else
      ratings = tastings.collect { |t| t.rating_final }
      avg_rating = ratings.inject(0.0) { |sum, elem| sum + elem } / ratings.length
      return avg_rating
    end
  end
  
  
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  # -- mobile device methods (from scottwb.com)
  before_filter :check_for_mobile
  
  # require 'zxing'
  # ZXing.decode '/Users/ecin/qrcode.png' #=> "QRcode string"
  
  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.order("name")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @wines }
    end
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
    @wine = Wine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @wine }
    end
  end

  # GET /wines/new
  # GET /wines/new.json
  def new
    @wine = Wine.new
    
    @vineyards_js = csv_array(Vineyard.where('name != ?', "").map{ |v| v.name },'"',",")
    @subregions_js = csv_array(Subregion.where('name != ?', "").map{ |v| v.name },'"',",")
    @regions_js = csv_array(Region.where('name != ?', "").map{ |v| v.name },'"',",")
    @countries_js = csv_array(Country.where('name != ?', "").map{ |v| v.name },'"',",")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @wine }
    end
  end
  
  def csv_array(myarr,appendage,delim)
    return '[' + myarr.map { |e| appendage + e + appendage }.join(delim) + ']'
  end

  # GET /wines/1/edit
  def edit
    @wine = Wine.find(params[:id])
    @heritage = @wine.get_heritage()
    
    @vineyards_js = csv_array(Vineyard.where('name != ?', "").map{ |v| v.name },'"',",")
    @subregions_js = csv_array(Subregion.where('name != ?', "").map{ |v| v.name },'"',",")
    @regions_js = csv_array(Region.where('name != ?', "").map{ |v| v.name },'"',",")
    @countries_js = csv_array(Country.where('name != ?', "").map{ |v| v.name },'"',",")
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(params[:wine].reject{ |k, v| ['vineyard', 'subregion', 'region', 'country'].include?(k) })
    Country.add_tuple(params[:wine][:vineyard], params[:wine][:subregion], params[:wine][:region], params[:wine][:country])
    v = Vineyard.find_by_name(params[:wine][:vineyard])
    @wine.vineyard_id = v.id

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, :notice => 'Wine was successfully created.' }
        format.json { render :json => @wine, :status => :created, :location => @wine }
      else
        format.html { render :action => "new" }
        format.json { render :json => @wine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wines/1
  # PUT /wines/1.json
  def update
    @wine = Wine.find(params[:id])

    respond_to do |format|
      if @wine.update_attributes(params[:wine].reject{ |k, v| ['vineyard', 'subregion', 'region', 'country'].include?(k) })
        format.html { redirect_to @wine, :notice => 'Wine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @wine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine = Wine.find(params[:id])
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url }
      format.json { head :no_content }
    end
  end
  
  # =================
  # guesser logic
  # =================

  # guesses vintage, displays tables to select of varietal and classification
  # (renders a javascript partial)
  def guesser
    @input_name = params[:input_name]
    unless @input_name == ""      
      @vintage = /[0-9]{4,4}/.match(@input_name)

      sorted_keywords = oneAndTwoWordStrings(params[:input_name]).sort
      @varietals = findVarietals(sorted_keywords) if sorted_keywords.length > 0
      @classifications = findClassifications(sorted_keywords) if sorted_keywords.length > 0
    end
    
    respond_to do |format|
      format.html{ render :partial => '/wines/guesser.js.erb', :layout => false }
      format.js{ render :partial => '/wines/guesser.js.erb', :layout => false }
    end
  end
  
  # matches varietal(s) from list
  def findVarietals(keywords)
    varietals = ["Aglianico", "Albarino", "Ansonica", "Arinto", "Arneis", "Barbera", "Cabernet Franc", "Cabernet Sauvignon", "Cannonau", "Carignane", "Carinena", "Carmenere", "Catawba", "Chardonnay", "Chasellas", "Chenin Blanc", "Cinsaut", "Cortese", "Corvina", "Counoise", "Dolcetto", "Ehrenfelser", "Fiano", "Folle Blanc", "Freisa", "Furmint", "Gamay", "Gewurztraminer", "Grechetto", "Grenache", "Kerner", "Lagrein", "Macebeo", "Malbec", "Malvasia", "Marsanne", "Mazuela", "Melon", "Merlot", "Montepulciano", "Moscato", "Mourvedre", "Muller-Thurgau", "Muscadet", "Muscat", "Nebbiolo", "Negroamaro", "Palomino", "Parellada", "Pedro Ximenez", "Petite Cabernet", "Petite Verdot", "Petite Vidure", "Petite Vidure", "Pinot Bianco", "Pinot Blanc", "Pinot Grigio", "Pinot Gris", "Pinot Meunier", "Pinot Noir", "Primitivo", "Prugnolo", "Rousanne", "Sangiovese", "Sauvignon Blanc", "Savagnin", "Scheurebe", "Schiava", "Semillion", "Seyval Blanc", "Sylvaner", "Syrah", "Temperanillo", "Traminer", "Trebbiano", "Ugni Blanc", "Verdiccio", "Vernaccia", "Viognier", "Viura", "Welschriesling", "Zinfandel"];
    return sortedArrayIntersection(varietals, keywords)
  end

  # returns tuples of form ["vineyard", "subregion", "region", "country"]
  # where any classification matches a keyword in input
  def findClassifications(keywords)
    sql_string = (["name LIKE ?"]*(keywords.length)).join(" OR ")
    sql_query = [sql_string] + keywords.collect { |k| "%#{k}%"}
    
    vineyards = Vineyard.find(:all, :conditions => sql_query)
    subregions = Subregion.find(:all, :conditions => sql_query)
    regions = Region.find(:all, :conditions => sql_query)
    countries = Country.find(:all, :conditions => sql_query)

    # { my_id => [my_name, my_other_id], ... }
    v_lookup = Hash[Vineyard.all.collect { |v| [f_attr(v, "id"), [f_attr(v, "name"), f_attr(v, "subregion_id")]] } ]
    s_lookup = Hash[Subregion.all.collect { |v| [f_attr(v, "id"), [f_attr(v, "name"), f_attr(v, "region_id")]] } ]
    r_lookup = Hash[Region.all.collect { |v| [f_attr(v, "id"), [f_attr(v, "name"), f_attr(v, "country_id")]] } ]
    c_lookup = Hash[Country.all.collect { |v| [f_attr(v, "id"), [f_attr(v, "name")]] } ]
    
    tuples = []
    [vineyards, subregions, regions, countries].flatten.each do |elem|
      v = v_lookup[elem.id] if elem.class == Vineyard
      s = s_lookup[elem.id] if elem.class == Subregion
      r = r_lookup[elem.id] if elem.class == Region
      c = c_lookup[elem.id] if elem.class == Country
      
      v ||= [""]
      s ||= (v != [""] ? s_lookup[v[1]] : [""])
      r ||= (s != [""] ? r_lookup[s[1]] : [""])
      c ||= (r ? c_lookup[r[1]] : [""])
      
      tuples.append([v[0], s[0], r[0], c[0]])
    end

  	return tuples
  end
  
  def f_attr(x, attr_name)
    return x[attr_name]
  end
  
  # return consecutive 1- and 2-word combinations in input string
  # min_word_length 
  def oneAndTwoWordStrings(str)
    min_word_length = 3
  	keywords = str.split(' ').reject{ |word| word.length < min_word_length }
    
  	n = keywords.length  
  	newwords = (0..(n-2)).collect { |i| keywords[i] + " " + keywords[i+1] }
  	return (keywords + newwords)
  end
  
  # return intersecting values of two sorted arrays. 
  # converts both to lower case (returns original of first array).
  def sortedArrayIntersection(arr1, arr2) 
  	i1 = 0
  	i2 = 0
  	intersection = []
    
  	while (i1 < arr1.length && i2 < arr2.length)
  		item1 = arr1[i1].downcase
  		item2 = arr2[i2].downcase
  		i1 = i1 + 1 if (item1 < item2)
      i2 = i2 + 1 if (item1 > item2)
      if item1 == item2
  			intersection.push(arr1[i1])
  			i1 = i1 + 1
        i2 = i2 + 1
  		end
  	end
    
  	return intersection
  end
    
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>
			
      <ul>
      <% @wine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  	
	<div class="field">
		<table class="noborder">
		  <tr>
		    <td><%= f.label :name %></td><td><%= f.text_field :name, :size => 100 %></td>
		  </tr>
		  <tr>
		    <td><%= f.label :price %></td><td><%= f.text_field :price, :size => 5 %></td>
		  </tr>
		  <tr>
		    <td><%= f.label :purchased %></td><td><%= f.text_field :purchased, :size => 100 %></td>
		  </tr>
		  <tr>
		    <td><%= f.label :vintage %></td><td> <%= f.number_field :vintage %></td>
		  </tr>
		</table>
	</div>
	
  
	<table id="wine_varietal_table">
		<thead><tr><th><%= f.label :varietal %></th></tr></thead>
		<tbody><tr><td><%= f.text_field :varietal %></td></tr></tbody>
	</table>
	
	<br />
	
  <table id="wine_classification_table">
		<thead>
			<tr>
				<th><%= f.label :vineyard %></th>
	      <th><%= f.label :subregion %></th>
	      <th><%= f.label :region %></th>
	      <th><%= f.label :country %></th>
				<th></th>
	    </tr>
		</thead>
	
		<tbody>
			<tr>
				<td>
					<input id="wine_vineyard" name="wine[vineyard]" 
					value="<%=(@heritage ? @heritage[:vineyard] : "" )%>" size="30" type="text">
				</td>
				<td>
					<input id="wine_subregion" name="wine[subregion]" 
					value="<%=(@heritage ? @heritage[:subregion] : "" )%>" size="30" type="text">
				</td>
				<td>
					<input id="wine_region" name="wine[region]" 
					value="<%=(@heritage ? @heritage[:region] : "" )%>" size="30" type="text">
				</td>
				<td>
					<input id="wine_country" name="wine[country]" 
					value="<%=(@heritage ? @heritage[:country] : "" )%>" size="30" type="text">
				</td>
				<td></td>
			</tr>
		</tbody>
	</table>
	
	<br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">

	var VINEYARDS = <%=raw(@vineyards_js)%>
	var SUBREGIONS = <%=raw(@subregions_js)%>
	var REGIONS = <%=raw(@regions_js)%>
	var COUNTRIES = <%=raw(@countries_js)%>
	var VARIETALS = ["Aglianico", "Albarino", "Ansonica", "Arinto", "Arneis", "Barbera", "Cabernet Franc", "Cabernet Sauvignon", "Cannonau", "Carignane", "Carinena", "Carmenere", "Catawba", "Chardonnay", "Chasellas", "Chenin Blanc", "Cinsaut", "Cortese", "Corvina", "Counoise", "Dolcetto", "Ehrenfelser", "Fiano", "Folle Blanc", "Freisa", "Furmint", "Gamay", "Gewurztraminer", "Grechetto", "Grenache", "Kerner", "Lagrein", "Macebeo", "Malbec", "Malvasia", "Marsanne", "Mazuela", "Melon", "Merlot", "Montepulciano", "Moscato", "Mourvedre", "Muller-Thurgau", "Muscadet", "Muscat", "Nebbiolo", "Negroamaro", "Palomino", "Parellada", "Pedro Ximenez", "Petite Cabernet", "Petite Verdot", "Petite Vidure", "Petite Vidure", "Pinot Bianco", "Pinot Blanc", "Pinot Grigio", "Pinot Gris", "Pinot Meunier", "Pinot Noir", "Primitivo", "Prugnolo", "Rousanne", "Sangiovese", "Sauvignon Blanc", "Savagnin", "Scheurebe", "Schiava", "Semillion", "Seyval Blanc", "Sylvaner", "Syrah", "Temperanillo", "Traminer", "Trebbiano", "Ugni Blanc", "Verdiccio", "Vernaccia", "Viognier", "Viura", "Welschriesling", "Zinfandel"];

	// copies name from [main wine form] to [guess form] before running guess method
	function beforeGuessing() {
		document.getElementById('input_name').value= document.getElementById('wine_name').value;

		// remove previous varietals, classifications
		var varietalTable = document.getElementById("wine_varietal_table");
		var classificationTable = document.getElementById("wine_classification_table");
		while (varietalTable.rows.length > 2) {
			varietalTable.deleteRow(2)
		};
		while (classificationTable.rows.length > 2) {
			classificationTable.deleteRow(2)
		};
	}

	// autocomplete for country, region, subregion, vineyard, varietal
	$(function() {
	  $( "#wine_country" ).autocomplete({ source: COUNTRIES });
	  $( "#wine_region" ).autocomplete({ source: REGIONS });
	  $( "#wine_subregion" ).autocomplete({ source: SUBREGIONS });
	  $( "#wine_vineyard" ).autocomplete({ source: VINEYARDS });

		$( "#wine_varietal" )
			.bind( "keydown", keepInWindow)
			.autocomplete( $.extend( autocompleteOptions,
					{source: sourceFunction(VARIETALS)}
				)
			)  
	});

</script>

app/views/wines/_guesser.js.erb
var varietalTable = document.getElementById("wine_varietal_table");
var classificationTable = document.getElementById("wine_classification_table");

// fill in varietals, use 1st guess
<% unless @varietals.nil? || @varietals.length == 0 %>
	<% @varietals.each do |v| %>
		addVarietal("<%=v%>");
	<% end %>
	useVarietal(0);
<% end %>

// fill in classifications, use 1st guess
<% unless @classifications.nil? || @classifications.length == 0 %>
	<% @classifications.each do |c| %>
		addClassification("<%=c[0]%>","<%=c[1]%>","<%=c[2]%>","<%=c[3]%>");
	<% end %>
	useClassification(0);
<% end %>

// fill in vintage
document.getElementById("wine_vintage").value = "<%=@vintage%>";

function addVarietal(v) {
  var rowCount = varietalTable.rows.length;
  var row = varietalTable.insertRow(rowCount);
	var i = rowCount - 2; // ith varietal 
	
  var cell0 = row.insertCell(0);
	cell0.innerHTML = '<a onclick="useVarietal('+i+')" id="varietal'+i+'">'+v+'</a>'
}

function useVarietal(i){
	document.getElementById("wine_varietal").value = $("#varietal" + i).html();
}

function addClassification(vineyard, subregion, region, country) {
  var rowCount = classificationTable.rows.length;
  var row = classificationTable.insertRow(rowCount);
	var i = rowCount - 2; // ith classification 
	
	var cell0 = row.insertCell(0);
	cell0.innerHTML = '<a onclick="useVineyard('+i+')" id="vineyard'+i+'">'+vineyard+'</a>'
	var cell1 = row.insertCell(1);
	cell1.innerHTML = '<a onclick="useSubregion('+i+')" id="subregion'+i+'">'+subregion+'</a>'
	var cell2 = row.insertCell(2);
	cell2.innerHTML = '<a onclick="useRegion('+i+')" id="region'+i+'">'+region+'</a>'
	var cell3 = row.insertCell(3);
	cell3.innerHTML = '<a onclick="useCountry('+i+')" id="country'+i+'">'+country+'</a>'
  var cell4 = row.insertCell(4);
	cell4.innerHTML = '<a onclick="useClassification('+i+')">use all</a>'
}

function useClassification(i){
	useVineyard(i);
	useSubregion(i);
	useRegion(i);
	useCountry(i);
}
function useVineyard(i) {
	document.getElementById("wine_vineyard").value = $("#vineyard" + i).html();
}
function useSubregion(i) {
	document.getElementById("wine_subregion").value = $("#subregion" + i).html();
}
function useRegion(i) {
	document.getElementById("wine_region").value = $("#region" + i).html();
}
function useCountry(i) {
	document.getElementById("wine_country").value = $("#country" + i).html();
}

app/views/wines/edit.html.erb
<h2>Edit wine</h2>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

app/views/wines/guesser.js.erb
var varietalTable = document.getElementById("wine_varietal_table");
var classificationTable = document.getElementById("wine_classification_table");

// fill in varietals, use 1st guess
<% unless @varietals.nil? || @varietals.length == 0 %>
	<% @varietals.each do |v| %>
		addVarietal("<%=v%>");
	<% end %>
	useVarietal(0);
<% end %>

// fill in classifications, use 1st guess
<% unless @classifications.nil? || @classifications.length == 0 %>
	<% @classifications.each do |c| %>
		addClassification("<%=c[0]%>","<%=c[1]%>","<%=c[2]%>","<%=c[3]%>");
	<% end %>
	useClassification(0);
<% end %>

// fill in vintage
document.getElementById("wine_vintage").value = "<%=@vintage%>";

function addVarietal(v) {
  var rowCount = varietalTable.rows.length;
  var row = varietalTable.insertRow(rowCount);
	var i = rowCount - 2; // ith varietal 
	
  var cell0 = row.insertCell(0);
	cell0.innerHTML = '<a onclick="useVarietal('+i+')" id="varietal'+i+'">'+v+'</a>'
}

function useVarietal(i){
	document.getElementById("wine_varietal").value = $("#varietal" + i).html();
}

function addClassification(vineyard, subregion, region, country) {
  var rowCount = classificationTable.rows.length;
  var row = classificationTable.insertRow(rowCount);
	var i = rowCount - 2; // ith classification 
	
	var cell0 = row.insertCell(0);
	cell0.innerHTML = '<a onclick="useVineyard('+i+')" id="vineyard'+i+'">'+vineyard+'</a>'
	var cell1 = row.insertCell(1);
	cell1.innerHTML = '<a onclick="useSubregion('+i+')" id="subregion'+i+'">'+subregion+'</a>'
	var cell2 = row.insertCell(2);
	cell2.innerHTML = '<a onclick="useRegion('+i+')" id="region'+i+'">'+region+'</a>'
	var cell3 = row.insertCell(3);
	cell3.innerHTML = '<a onclick="useCountry('+i+')" id="country'+i+'">'+country+'</a>'
  var cell4 = row.insertCell(4);
	cell4.innerHTML = '<a onclick="useClassification('+i+')">use all</a>'
}

function useClassification(i){
	useVineyard(i);
	useSubregion(i);
	useRegion(i);
	useCountry(i);
}
function useVineyard(i) {
	document.getElementById("wine_vineyard").value = $("#vineyard" + i).html();
}
function useSubregion(i) {
	document.getElementById("wine_subregion").value = $("#subregion" + i).html();
}
function useRegion(i) {
	document.getElementById("wine_region").value = $("#region" + i).html();
}
function useCountry(i) {
	document.getElementById("wine_country").value = $("#country" + i).html();
}

app/views/wines/index.html.erb
<h2>Wine list</h2>

<div class="field">
	<%= link_to 'Add a wine', new_wine_path %>
</div>

<div class="main_table">
	<% if @wines.nil? || @wines.length == 0 %>
		No wines exist yet. <%= link_to 'Click here', new_wine_path %> to add one.<br /><br />
	<% else %>
		<%= render :partial => 'wines/table', :locals => {:wines => @wines} %>
	<% end %>
</div>

app/views/wines/new.html.erb
<h2>Add a wine</h2>

<%= render 'form' %>

<%= link_to 'Back to all wines', wines_path %>

app/views/wines/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<% v = @wine.vineyard %>
<% s = v.subregion %>
<% r = s.region %>
<% c = r.country%>

<p>
  <b>Name:</b> 
	<%= @wine.name %>
</p>
<p>
  <b>Country:</b> 
	<%= link_to c.name, :controller => 'classification', :action => 'show', 
		:id => c.id, :type => c.class.to_s %>
</p>
<p>
  <b>Region:</b> 
	<%= link_to r.name, :controller => 'classification', :action => 'show', 
		:id => r.id, :type => r.class.to_s %>
</p>
<p>
  <b>Subregion:</b> 
	<%= link_to s.name, :controller => 'classification', :action => 'show', 
		:id => s.id, :type => s.class.to_s %>
</p>
<p>
  <b>Vineyard:</b> 
	<%= link_to v.name, :controller => 'classification', :action => 'show', 
		:id => v.id, :type => v.class.to_s %>
</p>
<p>
  <b>Vintage:</b> 
	<%= @wine.vintage %>
</p>
<p>
  <b>Varietal:</b> 
	<%= @wine.varietal %>
</p>
<p>
  <b>Price:</b> 
	<%= number_to_currency(@wine.price, :precision => 0) %>
</p>
<p>
  <b>Photo:</b> 
	<%= image_tag @wine.photo.url %>
</p>

<% if @wine.tastings.length == 0 %>
	This wine has not yet been reviewed. 
	<%= link_to 'Click here', {:controller => 'tastings', :action => 'new', 
		:wine_id_preselect => @wine.id} %> to add a tasting.<br /><br />
<% else %>
	<h3>List of tastings</h3>
	<%= render :partial => 'tastings/table', 
		:locals => {:tastings => @wine.tastings, :show_wine => false} %>
<% end %>
 
<%= link_to 'Edit wine', edit_wine_path(@wine) %> |
<%= link_to 'See all wines', wines_path %>